//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChamConggg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChamConggg()
        {
            this.BangLuongs = new HashSet<BangLuong>();
        }
    
        public string MaCC { get; set; }
        public string MaNV { get; set; }
        public Nullable<System.DateTime> NgayCC { get; set; }
        public string GioVaoLam { get; set; }
        public string GioTanLam { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BangLuong> BangLuongs { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
