//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.BangLuongs = new HashSet<BangLuong>();
            this.BaoHiemXaHois = new HashSet<BaoHiemXaHoi>();
            this.ChamCongs = new HashSet<ChamConggg>();
            this.HopDongNhanViens = new HashSet<HopDongNhanVien>();
        }
    
        public string MaNV { get; set; }
        public string MaPB { get; set; }
        public string MaCV { get; set; }
        public string MaLoai { get; set; }
        public string UserID { get; set; }
        public string HoTenNV { get; set; }
        public string CCCD { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string HocVan { get; set; }
        public string ChungChiNN { get; set; }
        public Nullable<System.DateTime> NgayVaoLam { get; set; }
        public Nullable<double> LuongCoBan { get; set; }
        public Nullable<double> HeSoLuong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BangLuong> BangLuongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaoHiemXaHoi> BaoHiemXaHois { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChamConggg> ChamCongs { get; set; }
        public virtual ChucVu ChucVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HopDongNhanVien> HopDongNhanViens { get; set; }
        public virtual MaLoaiNV MaLoaiNV { get; set; }
        public virtual PhongBann PhongBan { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
