//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLNhanSu_CNPMEntities1 : DbContext
    {
        public QLNhanSu_CNPMEntities1()
            : base("name=QLNhanSu_CNPMEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BangLuong> BangLuongs { get; set; }
        public virtual DbSet<BaoHiemXaHoi> BaoHiemXaHois { get; set; }
        public virtual DbSet<ChamConggg> ChamCongs { get; set; }
        public virtual DbSet<ChucVu> ChucVus { get; set; }
        public virtual DbSet<HopDongNhanVien> HopDongNhanViens { get; set; }
        public virtual DbSet<MaLoaiNV> MaLoaiNVs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhongBann> PhongBans { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<XepLoai> XepLoais { get; set; }
    
        public virtual int sp_ThemNhanVien(string maPB, string maCV, string maLoai, string hoTenNV, string cCCCD, string gioiTinh, Nullable<System.DateTime> ngaySinh, string diaChi, string hocVan, string chungChiNN, Nullable<System.DateTime> ngayVaoLam, Nullable<double> luongCoBan, Nullable<double> heSoLuong, string soDienThoai, string email)
        {
            var maPBParameter = maPB != null ?
                new ObjectParameter("MaPB", maPB) :
                new ObjectParameter("MaPB", typeof(string));
    
            var maCVParameter = maCV != null ?
                new ObjectParameter("MaCV", maCV) :
                new ObjectParameter("MaCV", typeof(string));
    
            var maLoaiParameter = maLoai != null ?
                new ObjectParameter("MaLoai", maLoai) :
                new ObjectParameter("MaLoai", typeof(string));
    
            var hoTenNVParameter = hoTenNV != null ?
                new ObjectParameter("HoTenNV", hoTenNV) :
                new ObjectParameter("HoTenNV", typeof(string));
    
            var cCCCDParameter = cCCCD != null ?
                new ObjectParameter("CCCCD", cCCCD) :
                new ObjectParameter("CCCCD", typeof(string));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var hocVanParameter = hocVan != null ?
                new ObjectParameter("HocVan", hocVan) :
                new ObjectParameter("HocVan", typeof(string));
    
            var chungChiNNParameter = chungChiNN != null ?
                new ObjectParameter("ChungChiNN", chungChiNN) :
                new ObjectParameter("ChungChiNN", typeof(string));
    
            var ngayVaoLamParameter = ngayVaoLam.HasValue ?
                new ObjectParameter("NgayVaoLam", ngayVaoLam) :
                new ObjectParameter("NgayVaoLam", typeof(System.DateTime));
    
            var luongCoBanParameter = luongCoBan.HasValue ?
                new ObjectParameter("LuongCoBan", luongCoBan) :
                new ObjectParameter("LuongCoBan", typeof(double));
    
            var heSoLuongParameter = heSoLuong.HasValue ?
                new ObjectParameter("HeSoLuong", heSoLuong) :
                new ObjectParameter("HeSoLuong", typeof(double));
    
            var soDienThoaiParameter = soDienThoai != null ?
                new ObjectParameter("SoDienThoai", soDienThoai) :
                new ObjectParameter("SoDienThoai", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemNhanVien", maPBParameter, maCVParameter, maLoaiParameter, hoTenNVParameter, cCCCDParameter, gioiTinhParameter, ngaySinhParameter, diaChiParameter, hocVanParameter, chungChiNNParameter, ngayVaoLamParameter, luongCoBanParameter, heSoLuongParameter, soDienThoaiParameter, emailParameter);
        }
    }
}
